### ISSUE TITLE
Could you please release the pytorch wheel built with cuda 11.1+?

### ISSUE THREAD

**Issue by syguan96** [intel-isl/open3d_downloads#2]
Hi all, really thanks for your huge contribution to the community! Yes, I met the problem -- `Compiling PyTorch ops with CUDA 11 may have stability issues. See Open3D issue #3324 and PyTorch issue #52663 for more information on this problem.` I have found the wheel of PyTorch 1.8.1 and  PyTorch 1.8.2 complied with CUDA 11.0. However, due to some reason, I have to use CUDA 11.1. I tried to build PyTorch from source code, but I failed. Could please upload a wheel complied with CUDA 11.1 (2,3,4)? Thanks very much!

**Comment by yxlao** [comment]
We have moved to PyTorch 1.12 in the master branch of Open3D. This new PyTorch does not require custom compilation, so we can directly used the official PyTorch release.
