### ISSUE TITLE
file DOWNLOAD HASH mismatch FOR Open3D-0.15.1 after today

### ISSUE THREAD

**Issue by RicardoM17** [intel-isl/open3d_downloads#4]
As of today I am getting the following error when trying to `make -j1`.

```
[  3%] Completed 'ext_nanoflann'
[  3%] Built target ext_nanoflann
-- Downloading https://github.com/isl-org/open3d_downloads/raw/master/RGBD/normal_map.npy to /Open3D-0.15.1/examples/test_data/open3d_downloads/RGBD/normal_map.npy
CMake Error at /Open3D-0.15.1/examples/test_data/download_test_data.cmake:30 (file):
  file DOWNLOAD HASH mismatch

    for file: [/Open3D-0.15.1/examples/test_data/open3d_downloads/RGBD/normal_map.npy]
      expected hash: [ce3eb60bef47179e9099bad2efecf76dac5cdb305c3c1dc45bd8dfd34502586f]
        actual hash: [e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855]
             status: [22;"HTTP response code said error"]

Call Stack (most recent call first):
  /Open3D-0.15.1/examples/test_data/download_test_data.cmake:48 (download_dataset_file)


CMakeFiles/open3d_downloads.dir/build.make:70: recipe for target 'CMakeFiles/open3d_downloads' failed
make[2]: *** [CMakeFiles/open3d_downloads] Error 1
CMakeFiles/Makefile2:927: recipe for target 'CMakeFiles/open3d_downloads.dir/all' failed
make[1]: *** [CMakeFiles/open3d_downloads.dir/all] Error 2
Makefile:155: recipe for target 'all' failed
make: *** [all] Error 2
```
The file in question is not properly downloaded given that it is empty.

Any help? @ssheorey you made a commit yesterday so I'm asking for your help directly if possible.

I don't think we really need this so we have:

```
DBUILD_EXAMPLES=OFF
DBUILD_TESTS=OFF
```
In the cmake options, but it still tries to download it. If the problem can't be fixed at the root and there's another way to resolve it,  I'm all ears

Thank you advance

**Comment by RicardoM17** [comment]
Edit: @ssheorey did you maybe rename `master` branch to `main` yesterday? If so all the urls in https://github.com/isl-org/Open3D/blob/v0.15.1/examples/test_data/download_file_list.json are now broken.

**Comment by ssheorey** [comment]
Hi @RicardoM17 thanks for reporting this issue.

Reverted branch name from main to master. Please check now.

**Comment by ssheorey** [comment]
PS: Please use the latest release instead of an older version of Open3D.

**Comment by RicardoM17** [comment]
> Hi @RicardoM17 thanks for reporting this issue.
> 
> Reverted branch name from main to master. Please check now.

It works again. Thanks @ssheorey 

> PS: Please use the latest release instead of an older version of Open3D.

Yes we are aware. We are in the process of fixing that but for many reasons it hasn't been possible to do it earlier.

Thank you for the quick help
